name: JS User Apply
description: 申请JS用户
labels: ["jsuser apply"]
body:
  - type: markdown
    attributes:
      value: "请按下列格式输入必要信息，否则不予通过申请。"
  - type: input
    attributes:
      label: 账号名称
      description: 输入你常用的账号名称。
    validations:
      required: true
  - type: input
    attributes:
      label: 机器ID
      description: 将EEWCN中关于框下方的ID粘贴到此处。
    validations:
      required: true
  - type: input
    attributes:
      label: 你从哪里获取的JS脚本文件？
    validations:
      required: true
  - type: input
    attributes:
      label: B站账号链接
      description: 在此处输入链接。
  - type: textarea
    attributes:
      label: 其他视频网站链接
      description: 如有抖音、快手等其他视频网站账号请一并给出。
  - type: textarea
    attributes:
      label: 你为什么要申请JS用户？
      description: 详细说明申请的理由，以及其他补充信息。
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 确认事项
      options:
        - label: 你使用的数据真实有效而非杜撰或哗众取宠
          required: true
        - label: 你确定如违反真实有效原则会被撤销ID
          required: true
    validations:
      required: true
